### ISSUE TITLE
Just report an issue, don't know where is the problem.

### ISSUE THREAD

**Issue by hongnod** [copperspice/cs_mingw_w64#2]
![image](https://user-images.githubusercontent.com/6680267/230807408-c8b8378a-cdae-4458-92fe-ee25094f3dc3.png)
试图访问无效的地址: An attempt was made to access an invalid address

**Comment by bgeller** [comment]
There is a bit of information missing. 

1  What project were you compiling

2  Was the program linking with CopperSpice or any libraries other than the C++ Standard Library 

3  What flags are you passing to the compiler  ( -m32, -O2  for example ) 

4   What version of Windows are you using

5   Do you have msys, msy2, or cygwin install on this computer?  If so they must be removed from your build path and Windows environment path.

**Comment by hongnod** [comment]
> There is a bit of information missing.
> 
> 1 What project were you compiling
> Build wxwidgets master.
> 2 Was the program linking with CopperSpice or any libraries other than the C++ Standard Library
> Only wxwidgets codebase
> 3 What flags are you passing to the compiler ( -m32, -O2 for example )
> cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=home_path/v3.3.x_mingw64_x64_static_mono -DwxBUILD_SHARED=OFF -DwxBUILD_SAMPLES=OFF -DwxBUILD_DEMOS=OFF -DwxBUILD_MONOLITHIC=ON -DwxUSE_STL=ON -DwxBUILD_COMPATIBILITY=3.2 -DwxUSE_OPENGL=OFF -DwxUSE_UNICODE_UTF8=ON
> 4 What version of Windows are you using
> Windows10 22H2.
> 5 Do you have msys, msy2, or cygwin install on this computer? If so they must be removed from your build path and Windows environment path.
     Yes. but not in all path.

**Comment by bgeller** [comment]
> 3 What flags are you passing to the compiler ( -m32, -O2 for example )

The reason we asked is because the image indicated you may be building for 32-bit, which we do not support at this time.  Our files only support 64-bit builds.  The text of "mingw32" and "i386"  indicate 32-bit.  For 64-bit you would see "x86_64".

> mingw32_gt_pch_use_adddress, at config/i386/host-mingw32.c

The other question is if the project you are compiling is using pre-compiled headers. If so, you will need to ensure these headers are being compiled again with our MinGW 10 compiler. We would suggest you turn off pre-compiled headers for right now. 


>5 Do you have msys, msy2, or cygwin install on this computer? If so they must be removed from your build path and Windows environment path.

>Yes. but not in all path.

The only way to ensure you are doing an accurate and valid test is to remove all of these folders from *every* path environment.  Mixing and matching of compiler Standard Library implementations does not work.

**Comment by hongnod** [comment]
It's cool.

Add -DCMAKE_DISABLE_PRECOMPILE_HEADERS=ON works with the cost of slow building.

BTW:  can you also add nasm into this toolkit, although it can be done by toolkit user, but with embedded one make it more complete.

**Comment by bgeller** [comment]
It sounds like you are able to build with our version of MinGW.  Can you confirm this.

Thank you so much for your continued dedication and testing.

**Comment by hongnod** [comment]
Yes, I can build wxWidgets with cs_mingw_w64 with CMake switch: CMAKE_DISABLE_PRECOMPILE_HEADERS=ON, Just do as your suggestion :"We would suggest you turn off pre-compiled headers for right now".
