### ISSUE TITLE
Why flex and pkg-config are pending ?

### ISSUE THREAD

**Issue by ghost** [copperspice/cs_mingw_w64#8]
I checked the edit history of this README.md file. These utilities are pending to be added for too long. What are the problems with them?

**Comment by ghost** [comment]
You can evaluate `u-config` from w64devkit as an alternative to pkg-config

**Comment by bgeller** [comment]
Adding certain utilities are not as simple as it looks. There is a lot of testing required.

**Comment by ghost** [comment]
> Adding certain utilities are not as simple as it looks. There is a lot of testing required.

Why don't you simply use MSYS2?

**Comment by bgeller** [comment]
Asking a question and then closing the ticket is considered unprofessional on github.  

Here is the answer for anyone looking at this later on. The MSys2 project is known to be a rolling release and not a stable platform. Developers could be on any random version.  Our CI requires consistent repeatable builds. 

The other issue is that MSys2 applies unapproved and unsupported patches to the GCC compiler and linker. Our CopperSpice teams choose to build a distribution from the upstream source.

**Comment by ghost** [comment]
You have never stated that your binary builds are reproducible. I'm not new to the concept, btw.

You can say the same about Arch Linux. Always update to the latest bits and you are OK. Arch is extremely stable for me.

All of the patches used by MSYS2 could be viewed on their Github. I don't think it's something that could change the behavior.

**Comment by bgeller** [comment]
When running CI reproducing the same result is a requirement for support of a given platform. This is the approach for every project, otherwise it is not reliable CI. 

The issues encountered with Msys2 are not just from our extensive research, others have observed the same behaviors. 
The software standards our team up holds are more strict than some other projects. This is why there are multiple projects for MinGW. Some do not include utilities in their distribution and simply release a compiler. 

Projects like CopperSpice need to have a defined list of which platforms they support, compilers, and compiler versions. As a user you are free to use any combination you want, however it becomes your responsibility to resolve any incompatibilities. If you are unable to do this, please contact our team privately so we can discuss paid support options. 

Thank you for taking the time to review and discuss your concerns.

Barbara
