### ISSUE TITLE
Bundle CMake and Ninja?

### ISSUE THREAD

**Issue by ghost** [copperspice/cs_mingw_w64#9]
Please look at the number of bundled utilities of Winlibs.com's MinGW-w64 distro:

CMake and Ninja are definitely not problematic (in case of licensing) to be included, otherwise they will not include them.

**Comment by ghost** [comment]
Git, Perl, and Python are not something essential to the development of CopperSpice based software than CMake and Ninja. IMO, CMake and Ninja should be bundled in your distro.

**Comment by bgeller** [comment]
I am not sure what Git has to do with your question.  However it is very relevant to the development of CopperSpice since this is the repository and source control system we use for every single project in our company. 

It would not make any sense to bundle CMake since there are a vast number of versions we support. It is not reasonable for us to assume that a developer is interested in using CMake 3.18 versus CMake 3.24. Developers like the ability to have a range of versions and choices.  Downloading from Kitware is very easy.
